apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-test
  name: http-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: http-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-test
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
          command: ["/bin/bash", "-c"] #override default command
          args: ["sleep 5; exit 1"] #sleep for 30 secs, then exit with an error
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 1
       maxSurge: 1
